#!/usr/bin/env node
// Builds piano/samples.js: a base64-embedded, multi-velocity-layer sample bank
// of the Salamander Grand Piano V3 (Alexander Holm, CC BY 3.0).
//
// Source: the npm packages @audio-samples/piano-mp3-velocity{N} (one per
// velocity layer, 1 = softest, 16 = hardest), which repackage the archive.org
// release as MP3. Each sample is re-encoded here to mono MP3, capped at
// MAX_SECONDS with a fade so the bank stays small enough to embed.
//
// Usage:  node tools/build-samples.mjs            (run from the piano/ folder)
// Needs:  node >= 18, npm, ffmpeg (with libmp3lame) on PATH.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pianoDir = join(here, "..");
const cacheDir = join(here, ".cache");
const outFile = join(pianoDir, "samples.js");

const LAYERS = [4, 8, 12, 16]; // Salamander velocity layers to embed
const PKG_VERSION = "1.0.5";
const MAX_SECONDS = 10;        // cap sample length (low notes ring ~25 s in the source)
const FADE_SECONDS = 3;        // fade-out length applied before the cap
const LAME_QUALITY = 3;        // libmp3lame VBR quality (0 = best, 9 = smallest)

// Salamander samples every minor third from A0 to C8 (30 notes).
const NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
const notes = [];
for (let midi = 21; midi <= 108; midi += 3) {
  notes.push({ midi, name: NOTE_NAMES[midi % 12] + (Math.floor(midi / 12) - 1) });
}

mkdirSync(cacheDir, { recursive: true });

function fetchLayer(layer) {
  const dir = join(cacheDir, `v${layer}`);
  if (existsSync(join(dir, "audio"))) return dir;
  console.log(`Downloading velocity layer ${layer} from npm...`);
  const tgz = execFileSync("npm", ["pack", `@audio-samples/piano-mp3-velocity${layer}@${PKG_VERSION}`, "--silent"], {
    cwd: cacheDir, encoding: "utf8",
  }).trim().split("\n").pop();
  mkdirSync(dir, { recursive: true });
  execFileSync("tar", ["-xzf", join(cacheDir, tgz), "-C", dir, "--strip-components=1"]);
  return dir;
}

function encode(src, dst) {
  if (existsSync(dst)) return;
  execFileSync("ffmpeg", [
    "-hide_banner", "-loglevel", "error", "-y", "-i", src,
    "-ac", "1", "-ar", "44100",
    "-af", `atrim=0:${MAX_SECONDS},afade=t=out:st=${MAX_SECONDS - FADE_SECONDS}:d=${FADE_SECONDS}`,
    "-codec:a", "libmp3lame", "-q:a", String(LAME_QUALITY),
    dst,
  ]);
}

const samples = {};
let totalBytes = 0;
for (const layer of LAYERS) {
  const dir = fetchLayer(layer);
  const encDir = join(cacheDir, `enc-v${layer}-q${LAME_QUALITY}-${MAX_SECONDS}s`);
  mkdirSync(encDir, { recursive: true });
  const available = new Set(readdirSync(join(dir, "audio")));
  for (const { name } of notes) {
    const srcName = `${name}v${layer}.mp3`;
    if (!available.has(srcName)) throw new Error(`missing ${srcName} in layer ${layer}`);
    const dst = join(encDir, `${name.replace("#", "s")}v${layer}.mp3`);
    encode(join(dir, "audio", srcName), dst);
    const bytes = readFileSync(dst);
    totalBytes += bytes.length;
    samples[`${name}v${layer}`] = bytes.toString("base64");
  }
  console.log(`Layer ${layer}: ${notes.length} samples encoded`);
}

const bank = {
  name: "Salamander Grand Piano V3",
  attribution: "Salamander Grand Piano V3 by Alexander Holm, CC BY 3.0 (https://creativecommons.org/licenses/by/3.0/)",
  source: "https://archive.org/details/SalamanderGrandPianoV3 via npm @audio-samples/piano-mp3-velocity*",
  mimeType: "audio/mpeg",
  channels: 1,
  layers: LAYERS,
  notes: notes.map((n) => n.midi),
  noteNames: notes.map((n) => n.name),
  samples,
};

const header = `// Generated by tools/build-samples.mjs - do not edit by hand.
// ${bank.attribution}
// ${LAYERS.length} velocity layers x ${notes.length} notes, mono MP3, max ${MAX_SECONDS} s each.
`;
writeFileSync(outFile, header + "window.PIANO_SAMPLE_BANK = " + JSON.stringify(bank) + ";\n");
console.log(`Wrote ${outFile}: ${Object.keys(samples).length} samples, ${(totalBytes / 1e6).toFixed(2)} MB of MP3, ` +
  `${(readFileSync(outFile).length / 1e6).toFixed(2)} MB on disk`);
