[package]
name = "solana-lamport-transfer"
version = "0.1.0"
edition = "2021"
description = "A native Solana program that transfers lamports through a CPI to the System Program"
license = "MIT"
repository = "https://github.com/Ohad-G-5790/solana-lamport-transfer"

[lib]
name = "solana_lamport_transfer"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
custom-heap = []
custom-panic = []

[dependencies]
solana-program = "2"
solana-system-interface = { version = "1", features = ["bincode"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
